version: '2'

services:

    php:
        build:
            context: ./php
            dockerfile: Dockerfile-80
        volumes:
            - ./app:/app
        tty: true

    ganache:
        build:
            context: ./ganache
            dockerfile: Dockerfile
        ports:
            - "8545:8545"
